### ISSUE TITLE
Incorrect _id field being used in SignupUserResponse

### ISSUE THREAD

**Issue by rolodato** [auth0/auth0.net#117]
Here's a sample response from `POST /dbconnections/signup`:

```json
{
  "_id": "573cea9ce0a882283e15f984",
  "email_verified": false,
  "email": "rodrigo@example.com"
}
```

However `SignupUserResponse` exposes the field `id`, which is never returned.

**Comment by SergeySorokin** [comment]
@rolodato, not only id is the issue. Username property of the class SignupUserResponse is empty as well.

**Comment by jerriep** [comment]
Hey guys, I am just busy with getting our ASP.NET Core samples and docs out at the moment. Is it OK if I look at this one for you next week?

**Comment by rolodato** [comment]
@SergeySorokin You are not receiving a username back because you are not sending a `username` property in the original request.

@jerriep If I understand correctly the only change would be to point to the `Id` property to the `_id` field of the JSON - anything else you can find that would need changing? I can send a PR for this if not.

**Comment by jerriep** [comment]
New package available on NuGet: https://www.nuget.org/packages/Auth0.AuthenticationApi

**Comment by SergeySorokin** [comment]
@rolodato , how do I pass username in teh request? 

Here is the definition for UserMaintenanceRequestBase class:
    //
    // Summary:
    //     Base class for user maintenance requests.
    public class UserMaintenanceRequestBase {
        public UserMaintenanceRequestBase();

        //
        // Summary:
        //     Gets or sets the client (app) identifier.
        [JsonProperty("client_id")]
        public string ClientId { get; set; }
        //
        // Summary:
        //     Gets or sets the connection.
        [JsonProperty("connection")]
        public string Connection { get; set; }
        //
        // Summary:
        //     Gets or sets the user's email address.
        [JsonProperty("email")]
        public string Email { get; set; }
        //
        // Summary:
        //     Gets or sets the user's password.
        [JsonProperty("password")]
        public string Password { get; set; }
    }

I suggest there is no property in SignupUserRequest class where username have to be assigned to. Why didn't you check it first before you ask me to set username. 

I suggest all the questions are due to absolutely poor documentation for .NET Authentication library usage. Is there any documentation and sample for utilization of SignupUserRequest? Could you please show me how username is passed?

I do sugn up with the following gist/snippet:
var response = await client.SignupUserAsync(new SignupUserRequest {
                    ClientId = ConfigurationManager.ClientId,
                    Connection = "Username-Password-Authentication",
                    Email = model.Email,                   
                    Password = model.Password
                });

Could you please change the gist to pass username.

**Comment by rolodato** [comment]
@SergeySorokin The current version of this library does not support creating users with usernames - that is another issue, so feel free to create one if you need that functionality. Auth0 will only return a `username` field if you are creating a user with a username, which is not your case.
