### ISSUE TITLE
Setting UserMetadata in Xamarin has different results

### ISSUE THREAD

**Issue by cschoede** [auth0/auth0.net#137]
The code below works in a basic Console Application. But doesn't work in a Xamarin.Forms Application.
```
var token = await GetJwtTokenAsync();
var manager = new ManagementApiClient(token.AccessToken, new Uri(""));

User user = await manager.Users.GetAsync(userId);
if (user == null)
{
    return null;
}

var request = new UserUpdateRequest
{
    Password = pin,
};

if (user.UserMetadata != null)
{
    user.UserMetadata.pin = null;
    request.UserMetadata = user.UserMetadata;
}

var result = await manager.Users.UpdateAsync(user.UserId, request);
return new ResponseModel
{
    IsSuccess = true,
    ErrorMessage = null,
    Content = user,
};
```

# Debug Info

## Console App

* **.NET Version:** 4.5.2
* **Auth0:** 3.6.0
* **Auth0.AuthenticationAPI:**: 3.7.0
* **Auth0.Core:** 3.7.0
* **Auth0.ManagementAPI:** 3.7.0
* **Netwonsoft.JSON:** 9.0.1

## Xamarin.Forms App

* **.NET Version:** 4.5
* **ASP.NET Core:** 1.0
* **Windows 8**
* **Windows 8.1**
* **Xamarin.Android**
* **Xamarin.iOS**
* **Xamarin.iOS (Classic)**
* **Xamarin.Mac**

Bug Discovered while testing against

7" Kitkat (4.4) XHDPI Tablet (Android 4.4 - API 19)

**Comment by jerriep** [comment]
Can you please expand on what you mean with "doesn't work"? 

Does it give you a compile time error? A runtime error? Or does it simply not update the metadata?

**Comment by cschoede** [comment]
When running the Console application and calling `user.UserMetadata.pin` in the `immediate window` produces the stacktrace below
```
{}
    First: '((Newtonsoft.Json.Linq.JToken)user.UserMetadata.pin).First' threw an exception of type 'System.InvalidOperationException'
    HasValues: false
    Last: '((Newtonsoft.Json.Linq.JToken)user.UserMetadata.pin).Last' threw an exception of type 'System.InvalidOperationException'
    Next: null
    Parent: {"pin": ""}
    Path: "pin"
    Previous: null
    Root: {{
  "name": "52",
  "pin": ""
}}
    Type: String
    Value: ""
    Results View: Expanding the Results View will enumerate the IEnumerable
    Dynamic View: Expanding the Dynamic View will get the dynamic members for the object
```
However when making that same call in the immediate window of the Xamarin Application gives `Unknown member: pin` and will throw an Exception.

**Comment by cschoede** [comment]
Actually, this is beginning to look like it's a JSON.NET issue and I'm fine bumping it there.

**Comment by jerriep** [comment]
Do you only get this exception when debugging? Or if you run the application normally as well? If you get it when running normally, then on what line exactly is the exception thrown?

I am asking because initially you said the code does not work. But now it seems that the code may be working, but instead you actually get an exception when trying to evaluate the value while debugging.

If you only get it while debugging, then it may have something to do with the way Xamarin behaves with a `dynamic` type in the debugger.

If so, can you please assign it to a temporary variable, and then evaluate that temporary variable, e.g.

```
string pin = user.UserMetadata.pin;
```

And then check the following:

1. Does that line throw an exception?
2. If it does not throw an exception, can you evaluate the value of the new `pin` string variable?

**Comment by jerriep** [comment]
This may be relevant to your specific case:
https://github.com/JamesNK/Newtonsoft.Json/issues/493

**Comment by cschoede** [comment]
@jerriep it would certainly appear so. I'll post the issue there.
