### ISSUE TITLE
Pulling Group Information from Azure Active Directory

### ISSUE THREAD

**Issue by jtainter** [auth0/auth0.net#138]
I've implemented connection to Azure Active Directory through Auth0 and am able to pull in the general user information but I can't seem to pull in any group information that we have associated to the users in Azure AD. 

I'm using the Auth0 Lock object for login and passing in scopes of 'openid groups profile'. After successful login Im capturing the claims that Auth0 is returning and none of them contain group information. In fact, originally I was only passing in openid for the scope and I get the same # of claims returned as I do when I pass in groups and profile.

In Auth0 I have an Enterprise Connection setup and talking to Azure AD no problem and in Azure AD I've tried modifying the permissions the Auth0 app has by granting read all groups permision to this connection.

My question is esssentially, is this even possible? I would think if you are integrating with Active Directory either on premise or hosted in Azure you would be able to get at this information. It seems the Authorization Plugin provided by Auth0 just allows you to manage group information directly in Auth0. We shouldn't have to do duplicated work, right?

Thanks

**Comment by jerriep** [comment]
This should work. Did you configure the Auth0 AD / LDAP Connector to map the groups from AD on your profile?

Please reference this document: 
https://auth0.com/docs/connector/modify#profile-mapper

In the "Profile Mapper" section of the AD Connector, you should ensure that you map the groups received from AD to the user profile, e.g.

```js
var profile = {
    id:          raw_data.objectGUID || raw_data.uid || raw_data.cn,
    displayName: raw_data.displayName,
    name: {
      familyName: raw_data.sn,
      givenName: raw_data.givenName
    },
    nickname: raw_data['sAMAccountName'] || raw_data['cn'] || raw_data['commonName'],
    groups: raw_data['groups'],
    emails: (raw_data.mail ? [{value: raw_data.mail }] : undefined)
  };
```

You can ensure that the groups are returned from AD by clicking the "Try" button in the Auth0 dashboard next to the AD Connection:

![image](https://cloud.githubusercontent.com/assets/1006420/22965045/ee3f2fd2-f39e-11e6-961a-b135969891d5.png)

The result which is returned should contain the groups, e.g.

![image](https://cloud.githubusercontent.com/assets/1006420/22965066/0ca833c4-f39f-11e6-97f6-605a772fe914.png)

Once you ensure that all of that is working, when you pass the `groups` scope, the groups should be returned in the `id_token`. You can debug the `id_token` to ensure that the claims are indeed present in the token by going to jwt.io and debugging the token, e.g.

![image](https://cloud.githubusercontent.com/assets/1006420/22965145/7678bda0-f39f-11e6-8516-9ea514c8bc03.png)

BTW, if you want to use the AD Connector in conjuction with the Authorization Extension you can also manage groups from AD to groups in the Authorization extension. You can read more in the "Access Control" section of this document:
https://auth0.com/docs/architecture-scenarios/application/web-app-sso

**Comment by jerriep** [comment]
@jtainter I have not heard back from you regarding this.

If you still  have issues, please feel free to contact Auth0 support

**Comment by jeson114** [comment]
+1 
I am unable to see the groups  for Azure AD .

**Comment by jerriep** [comment]
@jeson114 Can you please supply more information about your particular scenario? Did you follow the steps I outlined above?

**Comment by jeson114** [comment]
So i created an AD connection using [docs](https://auth0.com/docs/connections/enterprise/azure-active-directory/v2). 
Using the test button i was successfully able to login using my AD creds . 
I also enabled the Auth0 extension API with WebTask logs enabled (Also enable groups,roles,permisssion merge from AD in the extension ). The user object in the Rule did not contain groups or roles so that i can merge them onto the context.idToken
. 





![screen shot 2018-07-10 at 12 33 46 pm](https://user-images.githubusercontent.com/8187342/42494401-d4764e38-843d-11e8-87dd-901f277229e0.png)
![screen shot 2018-07-10 at 12 34 03 pm](https://user-images.githubusercontent.com/8187342/42494404-d6fc90ea-843d-11e8-9191-b84fc12d2e0e.png)

**Comment by jerriep** [comment]
@jeson114 So it appears as though the Azure groups are not coming through in the ID Token. It is not a problem with this library as such.

Check out the [AD Connector docs on Profile Mapping](https://auth0.com/docs/connector/modify#profile-mapper)

If that does not help you, please reach out on the [official Auth0 Support channel](https://support.auth0.com/). I can not assist you with the AD connector configuration and this is not the correct place to raise an issue with it.

**Comment by jeson114** [comment]
Thanks @jerriep . So what i did was, manually ran a rule that runs a request against azure to get membership .  I can then get the groups from that response . That might be a problem with the call that Auth0 is making to azure .

**Comment by jerriep** [comment]
@jeson114 Can you please explain why we need to open this issue?

My understanding of the situation is that the problem is that AD groups are not being populated in the actual ID Token being returned from Auth0, right? 

In that case, the issue is not with this library but on the Auth0 authentication side.

Unfortunately, I am not an Auth0 employee, so if my understanding is correct then I cannot help you. You will need to reach out to Auth0 support to assist you. They do not monitor these GH issues. You need to go through the proper support channels.

If the problem is with this library I will gladly reopen this issue.

**Comment by jeson114** [comment]
Ah my bad sorry . I didn't notice this repo was the library. I jumped head first here . Thanks @jerriep

**Comment by highflying** [comment]
@jerriep I'm having the same problem - did you get anywhere with Auth0 on getting it working?

**Comment by dhmistry3** [comment]
Is there a way to get the group ID and not just the name?
