### ISSUE TITLE
List users returns duplicates and is incomplete

### ISSUE THREAD

**Issue by WittrupA** [auth0/auth0.net#140]
I tried to create a list of all our users using the Management API v2. I assigned one hundred users per page. After 7 pages or so, I noted duplicates (e.g., a few users in a page had been listed in previous pages.) After completing the list, I noted that there were users who were not included in the entire, multi-page list.

When I created the list sorting on email address, I received all users, no duplicates. 

We have over 5,000 users. I did not test sorting on other fields.

**Comment by jerriep** [comment]
@WittrupA I will look into this for you

**Comment by jerriep** [comment]
Hi @WittrupA , I have an answer for you - which you may or may not like ;)

By default the returned users are sorted by the `last_login` field. In the case where a user has never logged in this value will be empty.

The problem with this however is that ElasticSearch will return these "non-sorted" ones randomly. This causes the inconsistency between queries which you are seeing.

Also note that because the default sort is `last_login` you will also get inconsistent results when a user logs in inbetween 2 queries you are making.

For now the best way around this is for you to always specify a sort field - something like the `user_id` for example which does not change.

1. I ask the documentation team to update the Management API documentation to reflect this problem
2. I will also investigate specifying a "default" sort order for the .NET SDK to work around the underlying problem in the Management SDK itself. This however may break existing users who rely on the current sort order. I will need to do investigation before committing to this.

**Comment by WittrupA** [comment]
Thanks @jerriep. I appreciate the response. Updating the documentation will allay all of my concerns. Frankly, I was curious about the default sort, and you've answered that. Good luck!
