### ISSUE TITLE
.Net Core 2.0

### ISSUE THREAD

**Issue by bialad** [auth0/auth0.net#156]
Are there any plans to move these libraries from netcoreapp1.1 to netcoreapp2.0? When I build the client application against 2.0, I get strange errors with your libraries.

Have you planned a conversion, the libraries haven't received commits in a few months?

**Comment by jerriep** [comment]
I assume you mean from .NET Standard 1.1 to .NET Standard 2.0?

There should not be any need, because .NET Standard 1.1 libraries will also work on .NET Core 2.0, whereas if we make these .NET Standard 2.0, then we limit many other users from using them.

Can you please be more specific as to what these errors are that you are getting?

If you do that then we can be better able to try and track down the real issue... If you can attach a project which reproduces the error, that would be great :)

**Comment by bialad** [comment]
Sorry, forgot how the netstandard works. You are absolutely right.

I tried running the restore and build in a container, and then it worked. I'm running dotnet cli on debian stretch, which has had some issues in the past.

After changing the permissions on the container generated .nuget and .dotnet folders is works outside on the container as well. I'll bring this up to the dotnet cli-team if it occurs again.
