### ISSUE TITLE
Guardian property is hidden on ManagementApiClient even though, GuardianClient is available

### ISSUE THREAD

**Issue by jaccus** [auth0/auth0.net#164]
I would like to use Guardian client, but I don't want to deal with IApiConnection and stuff.

Please uncomment your code that was poorly "hidden" in [https://github.com/auth0/auth0.net/commit/faa7af5228ee3415a2e5381d220041a0513a21db](https://github.com/auth0/auth0.net/commit/faa7af5228ee3415a2e5381d220041a0513a21db) :)

Would also appreciate some info on why was this hidden? Is this a buggy functionality? I'd rather not hit the Auth0 APIs bypassing this .NET library to keep it future-proof.

**Comment by jerriep** [comment]
@jaccus It was hidden because the team working on that was reworking the Guardian API completely. At the time no version of the Auth0.NET SDK was yet released with that Guardian functionality, so I just commented it out instead of deleting it completely. 

I will need to follow up with the Guardian team to find out the status of their APIs. I cannot just add it back until they give the go-ahead that their API surface is now stable

**Comment by jerriep** [comment]
@jaccus I received word back from Auth0 that a new Guardian API is forthcoming. So there is nothing we will do about this right now.

At the time when the new API is released I will do a proper update to support those new endpoints.

I will leave this issue open, but will close your PR for now

**Comment by jaccus** [comment]
So what you're basically saying is that you removed your Guardian v1 from SDK, before Guardian v2 was added, therefore you're making it impossible to work with Guardian v1 at this moment, even though it is the only way to deal with Guardian.

This does not sound like the right way to go about it - why not restore v1, and obsolete when v2 is available?

I can submit a support ticket via Auth0 tenant if that can help convince you :)

**Comment by jerriep** [comment]
The Guardian API was **never** added. 

I was working on adding it and then asked the team working on that some questions about the implementation. The Product Manager for Guardian asked me to hold off on releasing it as they were reworking the API completely.

You can see the commits for that class here:
https://github.com/auth0/auth0.net/commits/faa7af5228ee3415a2e5381d220041a0513a21db/src/Auth0.ManagementApi/Clients/GuardianClient.cs

In any case, at that point I have not released a version to NuGet, so I decided to just simpy comment out the property referencing the `GuardianClient` on the `IManagementApiClient` interface and `ManagementApiClient` class so no one can use it.

What I **did not** count on was an enterprising user like yourself discovering the `GuardianClient` class and trying to use that directly. That was my oversight, and has now placed us both in a bad spot.

The answer I got yesterday was that the updated version will be released **soon**. I won't quote the exact timeframe they gave me, because I don't want you to hold me to it since it is out of my control (but we are talking about a month - 2 months hopefully).

So opening a ticket will not really change anything. Please hold off on using it for now. If you have to absolutely use the Guardian endpoints, then please consider writing a small wrapper yourself for the time being.

**Comment by jaccus** [comment]
I see your point, if it was never released like you say.

Looks like I'll be better off stealing and tweaking your GuardianClient implementation to my own code, until you provide the v2.

**Comment by damieng** [comment]
Merged in, will be in next release.
