### ISSUE TITLE
EmailProviderCredentials uses wrong data type for SmtpPort

### ISSUE THREAD

**Issue by babelshift** [auth0/auth0.net#180]
This class:
https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/EmailProviderCredentials.cs

Should have SmtpPort as an int. Currently, when using the EmailProvider ConfigureAsync method, the resulting JSON request sent to the Auth0 API is treating this as a string. Because of this, this error is returned:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Payload validation error: 'Data does not match any schemas from 'oneOf'' on property credentials (Provider credentials).",
    "errorCode": "invalid_body"
}
```

**Comment by jerriep** [comment]
@babelshift I had to change it to a nullable int. This is to ensure that it is not always serialized. For example, if you configure the email provider as **mandrill**, then the `smtp_port` should not be set, otherwise it will also throw an error.

This change will go out in the next minor release. Thanks for reporting!

PS: The correct solution should be to create strongly typed `credentials` classes for each provider. Will add a task for this in the next major released.
