### ISSUE TITLE
Group Client

### ISSUE THREAD

**Issue by sofiaprice** [auth0/auth0.net#251]
I am planning to use Auth0 to manage groups of users, and associate these groups with roles, since I noticed it is a new feature of Auth0 and thought I should take advantage of it! I can see the role client has been added quite recently, and wondered if and when there are plans to add a similar client for Group management?

**Comment by damieng** [comment]
Hi.

As we have many SDKs and an ever-evolving management API we've been adding and updating individual SDKs on a somewhat ad-hoc basis depending on customer demand.

We plan on automatically code-generating much of the API in the future so that new endpoints automatically appear in all our management SDKs but this is still some way off.

Do you know specifically which endpoints you are looking for?  Is it just the two under https://auth0.com/docs/api/management/v2/#!/Groups/get_groups_by_id ?

**Comment by sofiaprice** [comment]
Hi,

Thanks for getting beck to me.

Yes, it was the two endpoints listed there, along with additional capacity for adding, removing creating groups (which I am aware is only supported by the Authorization Extension API).

For now I will just write my own small client for the endpoints, as that fits the time I have available better.

Thanks again for your response!

**Comment by damieng** [comment]
If you follow the pattern in auth0.net it should be pretty easy.  We'd also accept a PR :)

**Comment by damieng** [comment]
The Groups endpoint is no longer available so this would not make sense to add.
