### ISSUE TITLE
UserBlocks.GetByUserIdAsync is returning blocks for users with a duplicate username in the same tenant

### ISSUE THREAD

**Issue by scottyb86** [auth0/auth0.net#386]
### Description

When fetching the user blocks for a specific user using their userid, GetByUserIdAsync is returning user blocks for a separate user with a duplicate username in the same tenant

### Reproduction
Note - these steps were all taken within a single tenant.

1. Create a user against Connection1. I used the username "doubleuser"

2. Create a second user against Connection 2, and use the same username and password as the user you used for step one. (not sure if the password matters, but including it just in case)

3. Using the 'Try connection' method for connection1, attempt to login as the step1 user with the wrong password 10 times, so that user is blocked via bruteforce

4. Use the UserBlocks.GetByUserIdAsync function to load the userblocks for the user created in step two

Expected: No user blocks are returned
Actual: The user block from the user created in step 1 are returned

### Code sample:

IPagedList<User> auth0Users = await client.Users.GetAllAsync(getUsersRequest, pagination);

foreach (User user in auth0Users)
{
        UserBlocks currentBlocks = await client.UserBlocks.GetByUserIdAsync(user.UserId);
}

### Screenshots:

Screen shots showing the two users and their ids, including the user who is blocked.
![image](https://user-images.githubusercontent.com/1817622/78285158-8031b080-74ee-11ea-90a1-47830a4be80d.png)

![image](https://user-images.githubusercontent.com/1817622/78285186-83c53780-74ee-11ea-922d-496e2738873f.png)

screenshot showing the user id which is being passed
![image](https://user-images.githubusercontent.com/1817622/78285289-8cb60900-74ee-11ea-937a-7e28b510bbc8.png)

screenshot showing the blocks which are returned
![image](https://user-images.githubusercontent.com/1817622/78285855-b8d18a00-74ee-11ea-8ce5-b0262b26e8c6.png)

### Environment
Version 7.0.1

**Comment by damieng** [comment]
I was able to reproduce this problem independently of this SDK using the REST endpoints directly - I'm reaching out to the team that owns user blocking for more details on how this should behave.

**Comment by damieng** [comment]
Given that it's not SDK-specific and relates to another team the best course of action here is to file a support ticket at https://support.auth0.com/tickets so the correct team can continue the investigation for you.

**Comment by jmangelo** [comment]
Just for future reference and in the interest of transparency, the behavior of that endpoint although indeed very confusing is as originally designed.

In essence, that endpoint is merely a shortcut to get all blocks associated with the login identifiers of the specified user. For example, if user with `user_id: "auth0|x"` has `email: "john@example.com"` and `username: "john"` the endpoint will retrieve any blocks associated with either the email address or the username in question. This means that blocks for those login identifiers may be associated with connections doe which the user itself is not.

The above is confusing, but has certain legacy reasons so any changes also imply a formal deprecation of the current behavior which for now is not planned. The recommendation would be for anyone else facing this to raise your opinion through auth0.com/feedback in order to raise the priority of the situation and for a formal deprecation to be considered.
