### ISSUE TITLE
Add an interface for ManagementApiClient

### ISSUE THREAD

**Issue by hunteraj** [auth0/auth0.net#417]
### Describe the problem you'd like to have solved
Unit testing classes that depend upon ManagementApiClient is difficult. Because the client has no interface, it can't be mocked. This means extra measures have to be taken to isolate this dependency.

### Describe the ideal solution
Extract an interface, IManagementApiClient, so that the client can be properly mocked.

This is already exists for AuthenticationApiClient.

## Alternatives and current work-arounds
If using Visual Studio, fake assemblies can be used.

**Comment by damieng** [comment]
While AuthenticationApiClient is suitable for having an interface type unfortunately ManagementApiClient is not because it contains 19 properties that would have to also be exposed as interfaces and the resulting interface would contain over 100 methods. Additionally every time we add a new field, property or endpoint to the interface (which happens often) it would be a breaking change.

Instead we recommend you take a hard dependency on ManagementApiClient itself and instead mock IManagementApiConnection which does all the work and only requires two methods be mocked/stubbed and does not break when we add new endpoints. More details can be found at https://auth0.github.io/auth0.net/#mocking-the-managementapiclient

**Comment by stevehobbsdev** [comment]
@hunteraj What @damieng has suggested aligns with our direction here, so I will close this for now. His suggestion of using `ManagementApiClient` and mocking `IManagementApiConnection` feels like the right approach here, but feel free to continue the conversation if you feel this does not unblock you.
