### ISSUE TITLE
.net 5

### ISSUE THREAD

**Issue by MannusEtten** [auth0/auth0.net#458]
are there any plans , and if so what is the timeline, for the upgrade of all .net-libraries (core, cliet,wpf) to be upgraded to .net 5?

**Comment by frederikprijck** [comment]
@MannusEtten, as you are referring to WPF, could it be the case that you are using https://github.com/auth0/auth0-oidc-client-net and not Auth0.NET?

**Comment by Hawxy** [comment]
This library and the OIDC libraries already target .NET Standard or .NET Core and thus should already be compatible with .NET 5 🤔

**Comment by MannusEtten** [comment]
@Hawxy @frederikprijck yeah i need both libraries. And the interesting thing is that they target .net standard 2.
.Net standard 2 doesnt work with .net5 but with .net core 3.1.

So if both would have targeted .net standard 2.1 I would have probably not run into issues.

**Comment by Hawxy** [comment]
> .Net standard 2 doesnt work with .net5 but with .net core 3.1.

It works fine, the whole point of .NET Standard is to provide a common API that works across multiple runtimes and versions of .NET. Everything back to .NET Standard 1.0 works with .NET 5. Take a look at: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

I've been using Auth0.NET with .NET 5 since preview 2. If you're running into problems, it has nothing to do with the targeting of this library.

**Comment by frederikprijck** [comment]
For reference, I added a comment on the current state of things with the OIDC Client: https://github.com/auth0/auth0-oidc-client-net/issues/167#issuecomment-747322648

Closing this issue as Auth0.NET works in .NET5.
