### ISSUE TITLE
Add rules_config to SDK

### ISSUE THREAD

**Issue by colinbobolin** [auth0/auth0.net#542]
### Describe the problem you'd like to have solved

I am trying to write a script that will manage copying rules across tenants. For this to work properly, I'd also like to be able to update the [rules_config variables](https://auth0.com/docs/api/management/v2#!/Rules_Configs/put_rules_configs_by_key). I do not see this endpoint available using the auth0.net SDK.

### Describe the ideal solution
These rules_config endpoints are added to the SDK

**Comment by frederikprijck** [comment]
Hello,

Sorry for the very late reply. We have looked at this internally, and since Rules will be deprecated in favor of Actions, we prefer not to add additional methods to our SDK for things that are being deprecated.

I understand this isn't convenient for you, but I would advise to migrate to Actions regardless, more on this here: https://auth0.com/docs/customize/actions/migrate-from-rules-to-actions

**Comment by frederikprijck** [comment]
We will be adding support for this when https://github.com/auth0/auth0.net/pull/552 is merged!
