### ISSUE TITLE
Handle extra data returned from user profiles

### ISSUE THREAD

**Issue by advancedrei** [auth0/auth0.net#57]
Auth0's APIs don't presently have a way to delineate information that has been "normalized" from the rest of the properties returned from specific login providers. This means that the User payload from a Google login is vastly different from the User payload for a LinkedIn login.

This is going to create a problem for the .NET API, as the present V2 techniques will not make that data available to the developer; whatever properties are not mapped to an object will be ignored, and the raw payload will not be available either, so the end user won't be able to take advantage of the data (and to some developers monitoring HTTP requests, it may appear to them to be an error.

There are several options for handling this, and feel free to suggest others.
1. Change the way the results are processed on Auth0's servers, so that non-normalized profile properties are dumped in a different bucket, similar to the way app_metadata and user_metadata are presently handled. (This is the best option, because it will provide the most consistent experience to ALL Auth0 users.)
2. Leverage built-in PortableRest methods of getting the serialization result AND the raw request to load up a JObject with the raw result after the User object has been de-serialized. Then, use a LINQ query to get all non-normalized properties and dump them to a dynamic object on User called "ProviderUserData" (or something like that).
3. Same as 2, but try to serialize the remaining properties into provider-specific objects (Like "FacebookProviderUserData")
4. Leverage some of the built-in stuff in JSON.NET to plug some variation of Option 2 or Option 3 into *its* deserialization process, so that calls to the User APIs return either 
  * provider-specific User objects, like FacebookUser or GoogleUser, or 
  * regular User objects with strongly-typed provider-specific metadata objects.

I personally prefer strongly-types objects to something that could more easily fail at runtime. I'm assuming the Auth0 API can't return XML, so either parsing the payload manually or using JSON.NET Converters are viable options. Just depends on which one is better for architecture/perf.

**Comment by jerriep** [comment]
@advancedrei I am busy looking into this one and want to test the different scenarios. I am thinking of making use of a `dynamic` object.

Can you please tell me the API endpoints (or flow of API endpoints) you are referring to specifically?

**Comment by jerriep** [comment]
Currently this is not implemented. `dynamic` won't really work because we cannot make the entire class `dynamic`. It was previously suggested that ExpandoObject was used before. This needs more investigation.

**Comment by jerriep** [comment]
@ntotten I am looking into this and liking Option 2 which @advancedrei suggested above. I would however need to identify which properties are "standard" to a user and which properties are added by the specific services such as FB and Google.

Is there anyone on your side who can help me with this information?

**Comment by advancedrei** [comment]
I think, in a perfect world, it would be much better to have provider-specific extended properties classes, that way everything would be strongly-typed, and you could know "Hey, this was a Facebook profile, so I can see which of my friends also use this app". The problem would be, what do di if you've linked multiple profiles together.

**Comment by ntotten** [comment]
Details for profile are here: https://auth0.com/docs/user-profile#normalized-user-profile

There aren't too many standard fields. I wouldn't even try to provide a strongly typed object for any of the providers - that will be impossible to keep up with. 

The object will look essentially like this.

```
var user = new User();
string firstName = user.FirstName;
string lastName = user.LastName;
// more fields

foreach (var identity in user.Identities) {
   string provider = identity.Provider;
   var obj = identity.field1; // JObject or whatever
}
```

**Comment by advancedrei** [comment]
@ntotten That documentation is not accurate. I found fields that have wince been found to be consistent between providers. And it wouldn't be impossible to keep up with if done properly, like through code gen.

**Comment by ntotten** [comment]
What is the issue with the docs? We need to get it fixed if it is wrong. :)

I suppose you are right if you used codegen you could generate some of the objects. However, some providers (Particularly enterprise ones, will always need to be more dynamic because we dont know what the fields might be).

My opinion is to do what we did with the Facebook C# SDK. Build it to be a flexible object by default, but allow people to plug in strongly typed objects if they choose. I would be very leary of shipping the objects with the SDK though. I just dont think we have the resources at the time to keep it fully up to date or to generate them (even that will require some maintenance).

**Comment by jerriep** [comment]
Thank you for that link @ntotten 

I agree that to try and keep up and tryining to stay in sync with the various OAuth services will be a nightmare.

The approach the ASP.NET OAuth providers took was to add the basic properties to the context returned after authorization, and then add the actual object returned from the provider as a `JObject`:
https://github.com/aspnet/Security/blob/7a23028527d6aaf3d468a8d943a118a0c751f523/src/Microsoft.AspNet.Authentication.OAuth/Events/OAuthCreatingTicketContext.cs#L93

We can take a similar approach.

**Comment by jerriep** [comment]
OK, so I have played around today trying a few possible solutions to this. In the process I have stumbled across a JSON.NET feature called the `JsonExtensionDataAttribute` (look at the sample towards the bottom of this document: http://www.newtonsoft.com/json/help/html/SerializationAttributes.htm)

What it allows us to do is to create a property on the `User` class and mark it with this attribute, eg:

```
[JsonExtensionData]
public IDictionary<string, JToken> ExtraFields { get; set; }
```

Then during deserialization all these extra properties in the JSON structure which is not in our class as part of the standard user profile will be added to this dictionary.

I tested it and it works great. Because the value is a JToken it can contain complex structures like the ones which the LinkedIn users have - for example the location property:

![image](https://cloud.githubusercontent.com/assets/1006420/12328193/f72a03f6-bae2-11e5-88a3-bc5e26d7c204.png)

Only thing is that this is only done for reading. We cannot use it to add / update any of those fields back to Auth0.

Does this seem like a solution that everyone can live with?

**Comment by ntotten** [comment]
This looks great!

**Comment by advancedrei** [comment]
I think that this is a very good alternative. At the very least, it makes the data available in a way that it can be converted to a strongly-typed object, a la stripe.net's web hook events implementation.

Question: is there any way to be able to have the root API specify for the end users which providers the user data points are coming from? That way I could check the string array for "facebook" and/or "linkedin", without having to test for provider-specific properties?

**Comment by jerriep** [comment]
Robert, are you talking about the actual backend API potentially surfacing this detail?

**Comment by jerriep** [comment]
@advancedrei I closed this issue because the original issue has now been resolved. Depending on your requirements for your question above, we will open a new issue
