### ISSUE TITLE
PasswordChangeRequestTicket is missing Connection parameter

### ISSUE THREAD

**Issue by Dan3090** [auth0/auth0.net#691]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

**Description**
The Auth0 documentation mentions the possibility of adding a connection_id for the Auth0 database when creating a password change ticket using the Auth0 Management API. However, despite providing all required information, a 400 Bad Request error is encountered, and the response indicates that the "connection is required."

Upon adding the field "connection": "<DatabaseName>",, the request succeeds with a 200 status. This issue persists when using the Auth0.ManagementApi library.

**Expected Behavior**
The expectation is to include a Connection property on the PasswordChangeTicketRequest class.

**Reproduction Steps**
No specific reproduction steps mentioned.

**Environment**
Version of this library used: 7.25.1
Framework: .NET 6.0

**Additional Information**
No other relevant modules, plugins, or libraries are involved.

### Reproduction

Follow the steps on https://auth0.com/docs/authenticate/database-connections/password-change

### auth0.net version

7.25.1

### .NET version

6.0

**Comment by frederikprijck** [comment]
I am not sure I understand what you are saying.

In order to change the password using our SDK, you can:

- Call [ChangePasswordAsync](https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/AuthenticationApiClient.cs#L77): 
- This takes a parameter of type [ChangePasswordRequest](https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/Models/ChangePasswordRequest.cs)
- Which extends [UserMaintenanceRequestBase](https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/Models/UserMaintenanceRequestBase.cs) and contains [Connection](https://github.com/auth0/auth0.net/blob/master/src/Auth0.AuthenticationApi/Models/UserMaintenanceRequestBase.cs#L20).

This would allow you to do exactly what is explained in https://auth0.com/docs/authenticate/database-connections/password-change.

> The expectation is to include a Connection property on the PasswordChangeTicketRequest class.

PasswordChangeTicketRequest is not used for achieving the same thing as explained in the link you shared.
Instead, it is used to call [the `tickets/password-change` endpoint](https://auth0.com/docs/api/management/v2/tickets/post-password-change). This has no `connection` property, but only connection_id, [which we support](https://github.com/auth0/auth0.net/blob/master/src/Auth0.ManagementApi/Models/PasswordChangeTicketRequest.cs#L27).

Closing, as it looks like everything works as expected. Can always reopen if needed.
