### ISSUE TITLE
Add "type" parameter to CreatePasswordChangeTicketAsync 

### ISSUE THREAD

**Issue by fekberg** [auth0/auth0.net#717]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0.net#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.net/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.net/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

To use the password change ticket as a user invitation a query parameter has to be added.

### Describe the ideal solution

Allow an overload that sets `#type=invite` see here: https://auth0.com/docs/customize/email/send-email-invitations-for-application-signup#add-query-parameters-ticket-url

**Comment by kailash-b** [comment]
Hi @fekberg 

The SDK implementation is to mirror the underlying ManagementAPI, in this case `v2/tickets/post-password-change`. 

Adding an overload might not be a good idea in our context, since the query parameter could be anything and there could be some other things that other users might want to use. (type could just be one example). 
Also these are not supported by the [ManagementAPI](https://auth0.com/docs/api/management/v2/tickets/post-password-change) which means the onus will fall on the SDK to maintain it. 

Exposing an overload that's not supported by the ManagementAPI can in some sense also bring in chances of having a future change that could break the behaviour. 

We suggest you could have a wrapper around the method on your end to handle this.
Thanks for reaching out!
